# Generated by Django 5.0.4 on 2024-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
