# Generated by Django 5.0.4 on 2024-04-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ticket_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.spectator'),
        ),
    ]
