# Generated by Django 5.0.4 on 2024-04-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_schedule_ticket_price_alter_bookedseat_booked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemasIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
    ]
